### ISSUE TITLE
请问是否可以用领域数据进行增量预训练呢？

### ISSUE THREAD

**Issue by listwebit** [wenge-research/YAYI2#8]
1.我看只有微调的数据，是否支持用领域数据进行增量预训练呢？
2.如果支持应该怎么做或者怎么修改代码呢？
3.如果不支持为什么呢？

**Comment by wenge-research** [comment]
支持，需要自行修改loss计算的逻辑，对输入整体计算loss而不是像sft一样针对每一轮answer。
